const layouts=['Foundation','Dial','Information','List','Bottom actions','Pinned action'];
function WatchGrid({kind}:{kind:number}){return <svg className="travel-grid-watch" viewBox="0 0 140 172" role="img" aria-label={`Recreated ${layouts[kind].toLowerCase()} watch layout`}>
 <rect x="5" y="5" width="130" height="162" rx="32" fill="#101112" stroke="#e38465" strokeWidth=".8"/>
 <g fill="none" stroke="#60b16c" strokeWidth=".45"><rect x="14" y="16" width="112" height="140" rx="2"/>{[14,42,70,98,126].map(x=><path key={x} d={`M${x} 16V156`}/>)}{[16,44,72,100,128,156].map(y=><path key={y} d={`M14 ${y}H126`}/>)}</g>
 {kind===1?<g fill="none" stroke="#60b16c" strokeWidth=".65"><circle cx="70" cy="86" r="56"/>{[[26,28],[114,28],[26,144],[114,144]].map(([cx,cy])=><circle key={`${cx}-${cy}`} cx={cx} cy={cy} r="12"/>)}</g>:kind===2?<g fill="none" stroke="#53b9c2" strokeWidth=".7"><path d="M14 28H126M14 52H126M14 110H126M14 138H126M70 110V156"/><circle cx="26" cy="28" r="12"/></g>:kind===3?<g><path d="M14 16H126V44H14Z" fill="#5bc2cc20"/><path d="M14 44H126M14 72H126M14 100H126M14 128H126" stroke="#7db6b9" strokeWidth=".7"/></g>:kind===4?<g fill="none" stroke="#60b16c" strokeWidth=".65">{[28,70,112].map(cx=><circle key={cx} cx={cx} cy="144" r="12"/>)}<path d="M14 128H126"/></g>:kind===5?<g><rect x="14" y="128" width="112" height="28" rx="14" fill="#5bc2cc20" stroke="#60c2cb" strokeWidth=".65"/><path d="M14 44H126" stroke="#60c2cb" strokeWidth=".65"/></g>:null}
 </svg>}
function IconGrid(){return <svg className="travel-icon-construction" viewBox="0 0 420 420" role="img" aria-label="Recreated circular icon grid with a centered location-person symbol"><g fill="none" strokeWidth=".65">{[190,142,100,48].map((r,i)=><circle key={r} cx="210" cy="210" r={r} stroke={i===0?'#e38465':'#448fcc'}/>)}<path d="M20 210H400M210 20V400" stroke="#448fcc"/></g><g fill="#7bc777"><circle cx="210" cy="187" r="24"/><path d="M162 250c0-54 96-54 96 0z"/></g></svg>}
function NavigationStudy(){return <div className="travel-navigation-studies">{['Title','Back','Actions','Confirm'].map((name,i)=><div key={name}><span className="travel-navigation-time">10:09</span><div>{i>0&&<span className="travel-native-control">‹</span>}<strong>{i===3?'Done':'Title'}</strong>{i===2&&<span className="travel-native-control">＋</span>}</div><small>{name}</small></div>)}</div>}
export default function TraceReferences(){return <section className="travel-references" id="references"><div className="trace-section-intro"><span className="trace-kicker">Construction studies</span><h2>watchOS layout studies</h2><p>Recreated grids compare the space available for dials, lists, and actions, alongside icon alignment and navigation.</p></div><div className="travel-reference-atlas"><figure className="travel-vector-board travel-atlas-layouts"><div className="travel-layout-studies">{layouts.map((name,i)=><figure key={name}><WatchGrid kind={i}/><figcaption>{name}</figcaption></figure>)}</div><figcaption>Layout families · content follows the task</figcaption></figure><figure className="travel-vector-board travel-atlas-icon"><IconGrid/><figcaption>Icon geometry · a shared center, an optical balance</figcaption></figure><figure className="travel-vector-board travel-atlas-navigation"><NavigationStudy/><figcaption>Navigation · time, title, and actions have separate roles</figcaption></figure></div><p className="travel-source-note">Recreated construction studies, not production templates. Trace uses a single widget entry point; it does not borrow the app’s navigation. <a href="https://developer.apple.com/design/human-interface-guidelines/designing-for-watchos/" target="_blank" rel="noreferrer">Apple design guidance ↗</a></p></section>}
