import {OriginalTraceStudy} from './TraceStudies';

export default function TraceLayoutStudy(){return <section className="trace-layout-story" aria-labelledby="trace-layout-title">
 <header className="trace-section-heading"><span className="trace-kicker">Dimensions</span><h2 id="trace-layout-title">Layout and spacing</h2><p>A Watch app and a Smart Stack widget have different content boundaries. These drawings separate system space from the component’s internal padding.</p></header>
 <div className="trace-layout-board">
  <figure className="trace-safe-area"><svg viewBox="0 0 210 250" role="img" aria-label="Schematic Watch app: outer display, reserved header, and inset content region"><rect x="15" y="8" width="180" height="228" rx="43" fill="#090909" stroke="#525255"/><path d="M38 42h134" stroke="#666" strokeDasharray="2 3"/><text x="166" y="33" textAnchor="end" fill="#eee" fontSize="9">10:09</text><rect x="32" y="53" width="146" height="155" fill="#69ca6506" stroke="#69ca65" strokeWidth=".6"/><path d="M105 53v155M32 130.5h146" stroke="#69ca65" strokeWidth=".4" opacity=".55"/><text x="105" y="119" textAnchor="middle" fill="#e9e9eb" fontSize="12">Content region</text><text x="105" y="146" textAnchor="middle" fill="#99999f" fontSize="9">Inside system boundaries</text><path d="M15 217h180" stroke="#666" strokeDasharray="2 3"/></svg><figcaption>Watch app · schematic</figcaption></figure>
  <figure className="trace-widget-grid"><div className="trace-measured-widget"><OriginalTraceStudy label="Trace spacing study"/><svg viewBox="0 0 330 135.2" aria-hidden="true"><rect x="21.5" y="11" width="287" height="112" fill="none" stroke="#6dbcdd" strokeWidth=".5"/><path d="M96.5 48h31v75h-31zM202.5 48h31v75h-31z" fill="#ef695619"/>{[21.5,127.5,233.5].map(x=><g key={x}><rect x={x} y="48" width="75" height="75" fill="none" stroke="#69ca65" strokeWidth=".45"/><path d={`M${x+37.5} 48v75M${x} 85.5h75`} stroke="#69ca65" strokeWidth=".3" opacity=".5"/></g>)}</svg></div><div className="trace-dimension-key"><span><i/>Content boundary</span><span><i/>Circular grid</span><span><i/>Space between readings</span></div><figcaption>Trace · enlarged construction study</figcaption></figure>
 </div>
 <div className="trace-layout-notes"><article><span>01 / System boundary</span><h3>Safe areas and content margins</h3><p>A safe area avoids system UI and display obstructions. A widget uses its own context-dependent content margins. The app diagram shows the distinction, not a production template.</p></article><article><span>02 / Component dimensions</span><h3>Insets and circular grid</h3><p>At a 330-unit drawing width, this recreation uses about 21.5 units at the sides and 75-unit faces. Equal gaps hold the group together. These are drawing measurements, not Apple-specified points.</p></article><article><span>03 / Readability</span><h3>Text at smaller sizes</h3><p>Keep the reading and its unit together. If larger text or a narrower surface breaks that relationship, simplify the content or choose another layout. A scaled web preview cannot validate wrist readability.</p></article></div>
 <p className="trace-layout-source">Applied from Apple’s <a href="https://developer.apple.com/design/human-interface-guidelines/layout" target="_blank" rel="noreferrer">layout guidance</a>, <a href="https://developer.apple.com/documentation/watchos-apps/supporting-multiple-watch-sizes" target="_blank" rel="noreferrer">Watch sizing guidance</a>, and <a href="https://developer.apple.com/documentation/widgetkit/preparing-widgets-for-additional-contexts-and-appearances" target="_blank" rel="noreferrer">widget content margins</a>. Native templates and device previews remain the next check.</p>
 </section>}
